steps:
- name: node:16
  entrypoint: npm
  args: ["install"]
- name: node:16
  entrypoint: npm
  args: ["run", "gcp"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"