const Abilities: string[] = ['AGL','DEX','END','KNW','SPR','STR'];
const Skills: string[] = [
    'Camouflage',
    'Climb',
    'Devices',
    'Find',
    'Hunt',
    'Jump',
    'Stealth',
    'Swim',
    'Thievery'
];
const Talents: string[] = [
    'Accurate Shot',
    'Accurate Strike',
    'Active Defense',
    'Agile Charge',
    'Alpine',
    'Ambush',
    'Amphiibious',
    'Arboreal',
    'Assult',
    'Awareness',
    'Backstep',
    'Battler',
    'Bladedancer',
    'Bladeflash',
    'Block',
    'Bloodstruck',
    'Bold',
    'Bribery',
    'Bull Rush',
    'Confine',
    'Counterattack',
    'Deceptive Strike',
    'Deflect',
    'Deft',
    'Die Hard',
    'Disguise',
    'Dodge',
    'Elusive',
    'Enhanced Disguise',
    'Far Shot',
    'Feint',
    'Flurry',
    'Fortress',
    'Freerunner',
    'Frostfoot',
    'Furious',
    'Harasser',
    'Hardened',
    'Heroic Attack',
    'Hit and Run',
    'Impact',
    'Impetuous',
    'Infiltrate',
    'Intensify Spell',
    'Leaper',
    'March',
    'Marksman',
    'Medicine',
    'Merchant',
    'Missle Parry',
    'Mountaineer',
    'Nimble',
    'Opportune Strike',
    'Parry',
    'Pouncer',
    'Power Attack',
    'Precise Shot',
    'Protector',
    'Punish',
    'Rapid Fire',
    'Rapid Reload',
    'Raven Stance',
    'Recover',
    'Reluctant',
    'Retrograde',
    'Re-engage',
    'Running Shot',
    'Scout',
    'Scrounge',
    'Sharpshooter',
    'Shield Bash',
    'Sergeant[Follower type]',
    'Sidestep',
    'Sniper',
    'Spellbender',
    'Spellblocker',
    'Spellbracer',
    'Spelldancer',
    'Spellguider',
    'Spellhammer',
    'Spell Riposte',
    'Spotter',
    'Steadfast',
    'Subdue',
    'Taunt',
    'Teammate[Type]',
    'Tough'
];

export  {Abilities, Skills, Talents};